# Generated by Django 6.0.3 on 2026-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("production", "生產 PRODUCTION"),
                            ("ecology", "生態 ECOLOGY"),
                            ("life", "生活 LIFE"),
                        ],
                        max_length=20,
                        verbose_name="主題",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="標題")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=200, verbose_name="副標題"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="說明"),
                ),
                ("image", models.ImageField(upload_to="slides/", verbose_name="圖片")),
                ("is_active", models.BooleanField(default=True, verbose_name="顯示")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "輪播圖片",
                "verbose_name_plural": "輪播圖片",
                "ordering": ["order"],
            },
        ),
    ]
