# Generated by Django 6.0.3 on 2026-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="cc_credit",
            field=models.CharField(
                blank=True,
                help_text="例：攝影 © 王小明 / CC BY 4.0，留空表示無需標註",
                max_length=300,
                verbose_name="創用CC來源標註",
            ),
        ),
    ]
