# Generated by Django 6.0.3 on 2026-03-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_heroslide_cc_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="image",
            field=models.ImageField(
                upload_to="static/image/slides/", verbose_name="圖片"
            ),
        ),
    ]
