# Generated by Django 6.0.3 on 2026-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_heroslide_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="活動名稱")),
                (
                    "title_2",
                    models.CharField(blank=True, max_length=200, verbose_name="副標題"),
                ),
                ("description", models.TextField(verbose_name="說明")),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="地點"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="顯示")),
            ],
            options={
                "verbose_name": "活動",
                "verbose_name_plural": "活動",
                "ordering": ["date"],
            },
        ),
    ]
