# Generated by Django 6.0.3 on 2026-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🌾",
                        help_text="直接貼上 emoji，例如 🌾 🛍️ 📷 ✨",
                        max_length=10,
                        verbose_name="圖示（Emoji）",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="01",
                        help_text="顯示用的編號，例如 01 02 03",
                        max_length=10,
                        verbose_name="編號",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="標題")),
                ("description", models.TextField(verbose_name="說明")),
                (
                    "link_text",
                    models.CharField(
                        default="了解更多",
                        help_text="例如：探索農產、瀏覽商品",
                        max_length=50,
                        verbose_name="連結文字",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(default="#", max_length=200, verbose_name="連結網址"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="特色標示（金框）"),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="例如：限定體驗，留空不顯示",
                        max_length=20,
                        verbose_name="標籤文字",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="顯示")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "服務項目",
                "verbose_name_plural": "服務項目",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="聯絡信箱"),
        ),
        migrations.AddField(
            model_name="activity",
            name="contact_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="聯絡人"),
        ),
        migrations.AddField(
            model_name="activity",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="聯絡電話"),
        ),
        migrations.AddField(
            model_name="activity",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="activities/", verbose_name="宣傳圖片"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="單日活動留空", null=True, verbose_name="結束日期"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="置頂推薦"),
        ),
        migrations.AddField(
            model_name="activity",
            name="link_url",
            field=models.CharField(
                blank=True, help_text="留空不顯示按鈕", max_length=200, verbose_name="報名/詳情連結"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="time",
            field=models.CharField(
                blank=True,
                help_text="例如：09:00 - 17:00",
                max_length=50,
                verbose_name="時間",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(verbose_name="活動日期"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(verbose_name="活動說明"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="顯示於首頁"),
        ),
    ]
