# Generated by Django 6.0.3 on 2026-03-29 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_serviceitem_activity_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceitem",
            name="number",
        ),
    ]
