# Generated by Django 6.0.3 on 2026-04-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_serviceitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='留空表示不限人數', null=True, verbose_name='人數上限'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗號分隔，例如：科技, USR, 體驗課程', max_length=200, verbose_name='標籤'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/activities/', verbose_name='宣傳圖片'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, help_text='(若為單日活動，可不填)', null=True, verbose_name='結束日期'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='顯示'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='報名/詳情連結'),
        ),
    ]
