# Generated by Django 6.0.3 on 2026-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activity_max_participants_activity_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='register_deadline',
            field=models.DateField(blank=True, help_text='留空表示不限截止日', null=True, verbose_name='報名截止日'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_name',
            field=models.CharField(max_length=50, verbose_name='聯絡人'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, help_text='單日活動留空', null=True, verbose_name='結束日期'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=100, verbose_name='地點'),
        ),
    ]
