# Generated by Django 6.0.3 on 2026-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, help_text='包含本人，例如全家4人填4', verbose_name='報名人數'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='note',
            field=models.TextField(blank=True, help_text='同行人姓名、飲食需求等', verbose_name='備註'),
        ),
    ]
