# Generated by Django 6.0.3 on 2026-04-02 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registration_participant_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_per_user',
            field=models.PositiveIntegerField(default=1, help_text='同一活動每人最多報名幾次', verbose_name='每人限報名次數'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='register_deadline',
            field=models.DateTimeField(blank=True, help_text='留空表示不限截止日', null=True, verbose_name='報名截止時間'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='信箱')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.registration', verbose_name='報名記錄')),
            ],
            options={
                'verbose_name': '同行人員',
                'verbose_name_plural': '同行人員',
            },
        ),
    ]
