# Generated by Django 6.0.3 on 2026-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activity_max_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(blank=True, help_text='例如：09:00 - 17:00', max_length=50, verbose_name='活動時間'),
        ),
    ]
