# Generated by Django 6.0.3 on 2026-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='宣傳圖片'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='slides/', verbose_name='圖片'),
        ),
    ]
