# Generated by Django 6.0.3 on 2026-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_activity_cover_image_alter_heroslide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='信箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('subject', models.CharField(max_length=100, verbose_name='主旨')),
                ('message', models.TextField(verbose_name='訊息內容')),
                ('status', models.CharField(choices=[('new', '未讀'), ('read', '已讀'), ('replied', '已回覆')], default='new', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送出時間')),
            ],
            options={
                'verbose_name': '聯絡訊息',
                'verbose_name_plural': '聯絡訊息',
                'ordering': ['-created_at'],
            },
        ),
    ]
