# Generated by Django 6.0.3 on 2026-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_registration_closed',
            field=models.BooleanField(default=False, help_text='勾選後立即停止報名，不論截止日期', verbose_name='強制關閉報名'),
        ),
    ]
