# Generated by Django 6.0.3 on 2026-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_activity_is_registration_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='留空表示不限制', null=True, verbose_name='每帳號限報名人數'),
        ),
    ]
