# Generated by Django 6.0.3 on 2026-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_activity_max_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='留空表示不限總人數', null=True, verbose_name='總人數上限'),
        ),
    ]
