# Generated by Django 6.0.3 on 2026-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_activity_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiotProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🐟', max_length=10, verbose_name='圖示（Emoji）')),
                ('title', models.CharField(max_length=100, verbose_name='專案名稱')),
                ('tags', models.CharField(help_text='例如：智慧養殖,水質監測', max_length=100, verbose_name='標籤')),
                ('description', models.TextField(verbose_name='專案說明')),
                ('link_url', models.CharField(blank=True, help_text='與在地故事結合的延伸連結', max_length=200, verbose_name='連結網址')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'USR AIoT 專案',
                'verbose_name_plural': 'USR AIoT 專案',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UsrAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('category', models.CharField(help_text='例如：社會實踐, AIoT 課程', max_length=50, verbose_name='分類/標籤')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('description', models.TextField(verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
            ],
            options={
                'verbose_name': 'USR 師生表現紀錄',
                'verbose_name_plural': 'USR 師生表現紀錄',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UsrTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role', models.CharField(help_text='例如：計畫主持人, 共同主持人', max_length=50, verbose_name='計畫角色')),
                ('department', models.CharField(max_length=100, verbose_name='系所/職稱')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
            ],
            options={
                'verbose_name': 'USR 計畫團隊',
                'verbose_name_plural': 'USR 計畫團隊',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UsrVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='發布日期')),
                ('title', models.CharField(max_length=150, verbose_name='影片標題')),
                ('link_url', models.CharField(max_length=300, verbose_name='影片連結')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
            ],
            options={
                'verbose_name': 'USR 影音紀錄',
                'verbose_name_plural': 'USR 影音紀錄',
                'ordering': ['-date'],
            },
        ),
    ]
