# Generated by Django 6.0.3 on 2026-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aiotproject_usrachievement_usrteammember_usrvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiotproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usr/aiot/', verbose_name='專案圖片'),
        ),
        migrations.AddField(
            model_name='usrachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usr/achievements/', verbose_name='活動照片'),
        ),
        migrations.AddField(
            model_name='usrachievement',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳細連結'),
        ),
    ]
