# Generated by Django 6.0.3 on 2026-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aiotproject_image_usrachievement_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsrTeamMember',
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='category',
            field=models.CharField(max_length=50, verbose_name='主題'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cc_credit',
            field=models.CharField(blank=True, max_length=300, verbose_name='創用CC來源標註'),
        ),
    ]
