# Generated by Django 6.0.3 on 2026-04-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_usrteammember_alter_heroslide_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order'], 'verbose_name': '首頁輪播', 'verbose_name_plural': '首頁輪播'},
        ),
    ]
