# Generated by Django 6.0.3 on 2026-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_heroslide_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsrTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role', models.CharField(max_length=100, verbose_name='稱謂/角色')),
                ('description', models.TextField(blank=True, verbose_name='介紹')),
                ('image', models.ImageField(blank=True, null=True, upload_to='usr/team/', verbose_name='成員照片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
            ],
            options={
                'verbose_name': 'USR 團隊成員',
                'verbose_name_plural': 'USR 團隊成員',
                'ordering': ['order'],
            },
        ),
    ]
