# Generated by Django 6.0.3 on 2026-04-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_usrteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('confirmed', '已確認'), ('waitlist', '候補中')], default='confirmed', help_text='confirmed=已確認, waitlist=候補中', max_length=10, verbose_name='報名狀態'),
        ),
    ]
