# Generated by Django 6.0.3 on 2026-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allow_waitlist',
            field=models.BooleanField(default=False, help_text='當名額不足時，是否允許轉為候補', verbose_name='允許候補'),
        ),
    ]
