# Generated by Django 6.0.3 on 2026-04-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_activity_allow_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrvideo',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細說明'),
        ),
        migrations.AddField(
            model_name='usrvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='usr/videos/', verbose_name='直接上傳影片檔'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='link_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='YouTube 連結'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='title',
            field=models.CharField(max_length=150, verbose_name='影片/紀錄標題'),
        ),
        migrations.CreateModel(
            name='UsrVideoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='usr/video_images/', verbose_name='圖片')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='圖片說明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.usrvideo', verbose_name='所屬紀錄')),
            ],
            options={
                'verbose_name': '影音紀錄附圖',
                'verbose_name_plural': '影音紀錄附圖',
                'ordering': ['order'],
            },
        ),
    ]
