# Generated by Django 6.0.3 on 2026-04-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_usrvideo_description_usrvideo_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrvideo',
            name='embed_code',
            field=models.TextField(blank=True, help_text='若 YouTube 連結被官方擋下，或是來自非 YouTube 平台的影片，請將外部的 <iframe> 原始碼直接貼在這裡', verbose_name='自訂嵌入原始碼'),
        ),
    ]
