# Generated by Django 6.0.3 on 2026-04-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usrvideo_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='link_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='報名/詳情連結'),
        ),
        migrations.AlterField(
            model_name='aiotproject',
            name='link_url',
            field=models.CharField(blank=True, help_text='與在地故事結合的延伸連結', max_length=1000, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='link_url',
            field=models.CharField(default='#', max_length=1000, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='usrachievement',
            name='link_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='詳細連結'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='link_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='YouTube 連結'),
        ),
    ]
