# Generated by Django 6.0.3 on 2026-04-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_activity_link_url_alter_aiotproject_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='報名/詳情連結'),
        ),
        migrations.AlterField(
            model_name='aiotproject',
            name='link_url',
            field=models.URLField(blank=True, help_text='與在地故事結合的延伸連結', max_length=500, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='link_url',
            field=models.URLField(default='#', max_length=500, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='usrachievement',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='詳細連結'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='embed_code',
            field=models.TextField(blank=True, help_text='可貼入 <iframe> 原始碼', verbose_name='自訂嵌入原始碼'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='YouTube 連結'),
        ),
    ]
