# Generated by Django 6.0.3 on 2026-04-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_activity_link_url_alter_aiotproject_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrvideo',
            name='embed_code',
            field=models.TextField(blank=True, help_text='可貼入來自 YouTube / Facebook 等平台的嵌入原始碼（iframe 格式）', verbose_name='自訂嵌入原始碼'),
        ),
    ]
