# Generated by Django 6.0.3 on 2026-04-11 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_usrvideo_embed_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('category', models.CharField(choices=[('important', '重要公告'), ('general', '一般訊息'), ('event', '活動快訊')], default='general', max_length=20, verbose_name='分類')),
                ('content', models.TextField(verbose_name='內容')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='發佈日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
                ('is_priority', models.BooleanField(default=False, verbose_name='置頂')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_priority', '-publish_date', '-created_at'],
            },
        ),
    ]
