# Generated by Django 6.0.3 on 2026-04-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notices/', verbose_name='圖片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='圖片說明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.notice', verbose_name='公告')),
            ],
            options={
                'verbose_name': '公告圖片',
                'verbose_name_plural': '公告圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
