# Generated by Django 6.0.3 on 2026-04-11 13:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_noticeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_activities, verbose_name='宣傳圖片'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='報名/詳情連結'),
        ),
        migrations.AlterField(
            model_name='aiotproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_usr_aiot, verbose_name='專案圖片'),
        ),
        migrations.AlterField(
            model_name='aiotproject',
            name='link_url',
            field=models.CharField(blank=True, help_text='與在地故事結合的延伸連結', max_length=500, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_slides, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='noticeimage',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_notices, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='link_url',
            field=models.CharField(default='#', max_length=500, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='usrachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_usr_achievements, verbose_name='活動照片'),
        ),
        migrations.AlterField(
            model_name='usrachievement',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='詳細連結'),
        ),
        migrations.AlterField(
            model_name='usrteammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_usr_team, verbose_name='成員照片'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='YouTube 連結'),
        ),
        migrations.AlterField(
            model_name='usrvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_usr_videos, verbose_name='直接上傳影片檔'),
        ),
        migrations.AlterField(
            model_name='usrvideoimage',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_usr_video_images, verbose_name='圖片'),
        ),
    ]
