# Generated by Django 6.0.3 on 2026-04-11 13:50

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_activity_cover_image_alter_activity_link_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsrAchievementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.upload_usr_achievement_images, verbose_name='圖片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='圖片說明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.usrachievement', verbose_name='所屬成果')),
            ],
            options={
                'verbose_name': '師生成果圖片',
                'verbose_name_plural': '師生成果圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
