# Generated by Django 6.0.3 on 2026-04-12 02:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_usrachievementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('local', '在地商家'), ('usr', '相關 USR 連結')], default='local', max_length=20, verbose_name='分類')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_related_links, verbose_name='連結圖片')),
                ('link_url', models.CharField(max_length=500, verbose_name='連結網址')),
                ('link_text', models.CharField(default='了解更多', max_length=50, verbose_name='按鈕文字')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '相關連結',
                'verbose_name_plural': '相關連結',
                'ordering': ['order', 'title'],
            },
        ),
    ]
