# Generated by Django 6.0.3 on 2026-06-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_relatedlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedlink',
            options={'ordering': ['order', 'title'], 'verbose_name': '在地商家與相關連結', 'verbose_name_plural': '在地商家與相關連結'},
        ),
    ]
