# Generated by Django 6.0.3 on 2026-04-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('slug', models.SlugField(unique=True, verbose_name='網址代稱')),
                ('category', models.CharField(choices=[('treasure', '三寶'), ('lightwall', '光雕牆'), ('temple', '廟宇'), ('origin', '聚落起源'), ('ecology', '生態'), ('usr', 'USR成果')], default='treasure', max_length=30, verbose_name='分類')),
                ('short_intro', models.CharField(blank=True, max_length=255, verbose_name='短介紹')),
                ('content', models.TextField(blank=True, verbose_name='詳細內容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='guide/story_spots/', verbose_name='封面圖片')),
                ('location_name', models.CharField(blank=True, max_length=100, verbose_name='地點名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精選')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '導覽點',
                'verbose_name_plural': '導覽點',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('fact_type', models.CharField(choices=[('history', '文史資料'), ('legend', '地方傳說'), ('guide', '導覽補充'), ('fun', '趣味小知識')], default='guide', max_length=20, verbose_name='內容類型')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='guide.storyspot', verbose_name='所屬導覽點')),
            ],
            options={
                'verbose_name': '導覽說明',
                'verbose_name_plural': '導覽說明',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ARAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='素材名稱')),
                ('asset_type', models.CharField(choices=[('video', '影片'), ('audio', '音訊'), ('image', '圖片'), ('model', '3D模型'), ('hybrid', '混合素材')], default='video', max_length=20, verbose_name='素材類型')),
                ('marker_image', models.ImageField(blank=True, null=True, upload_to='guide/ar/markers/', verbose_name='辨識圖片(marker)')),
                ('target_file', models.FileField(blank=True, null=True, upload_to='guide/ar/targets/', verbose_name='MindAR target 檔')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='guide/ar/videos/', verbose_name='影片檔')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='guide/ar/audios/', verbose_name='音訊檔')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='guide/ar/images/', verbose_name='圖片素材')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='guide/ar/models/', verbose_name='3D模型檔')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_assets', to='guide.storyspot', verbose_name='所屬導覽點')),
            ],
            options={
                'verbose_name': 'AR素材',
                'verbose_name_plural': 'AR素材',
                'ordering': ['id'],
            },
        ),
    ]
