# Generated by Django 6.0.3 on 2026-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arasset',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='static/image/guide/ar/audios/', verbose_name='音訊檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/guide/ar/images/', verbose_name='圖片素材'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='marker_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/guide/ar/markers/', verbose_name='辨識圖片(marker)'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='static/image/guide/ar/models/', verbose_name='3D模型檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='target_file',
            field=models.FileField(blank=True, null=True, upload_to='static/image/guide/ar/targets/', verbose_name='MindAR target 檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='static/image/guide/ar/videos/', verbose_name='影片檔'),
        ),
    ]
