# Generated by Django 6.0.3 on 2026-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_arasset_audio_file_alter_arasset_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyspot',
            name='cover_image_credit',
            field=models.CharField(blank=True, help_text='例：CC BY 2.0 / 攝影：王小明 / Wikimedia Commons', max_length=200, verbose_name='圖片來源'),
        ),
        migrations.AddField(
            model_name='storyspot',
            name='maps_url',
            field=models.URLField(blank=True, help_text='建議貼完整長網址 https://www.google.com/maps/place/... 而非短網址', verbose_name='Google Maps 連結'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='guide/ar/audios/', verbose_name='音訊檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='guide/ar/images/', verbose_name='圖片素材'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='marker_image',
            field=models.ImageField(blank=True, null=True, upload_to='guide/ar/markers/', verbose_name='辨識圖片(marker)'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='guide/ar/models/', verbose_name='3D模型檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='target_file',
            field=models.FileField(blank=True, null=True, upload_to='guide/ar/targets/', verbose_name='MindAR target 檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='guide/ar/videos/', verbose_name='影片檔'),
        ),
    ]
