# Generated by Django 6.0.3 on 2026-04-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_storyspot_cover_image_credit_storyspot_maps_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyfact',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '不重要_導覽說明', 'verbose_name_plural': '不重要_導覽說明'},
        ),
    ]
