# Generated by Django 6.0.3 on 2026-04-12 02:30

import guide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_storyfact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arasset',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=guide.models.upload_ar_audios, verbose_name='音訊檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=guide.models.upload_ar_images, verbose_name='圖片素材'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='marker_image',
            field=models.ImageField(blank=True, null=True, upload_to=guide.models.upload_ar_markers, verbose_name='辨識圖片(marker)'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to=guide.models.upload_ar_models, verbose_name='3D模型檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='target_file',
            field=models.FileField(blank=True, null=True, upload_to=guide.models.upload_ar_targets, verbose_name='MindAR target 檔'),
        ),
        migrations.AlterField(
            model_name='arasset',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=guide.models.upload_ar_videos, verbose_name='影片檔'),
        ),
        migrations.AlterField(
            model_name='storyspot',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=guide.models.upload_story_spots, verbose_name='封面圖片'),
        ),
    ]
