# Generated by Django 6.0.3 on 2026-06-09 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='map_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='池區地圖備註'),
        ),
        migrations.AddField(
            model_name='pond',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='water_ponds', to=settings.AUTH_USER_MODEL, verbose_name='可查看帳號'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ammonia_nitrogen',
            field=models.FloatField(blank=True, null=True, verbose_name='氨氮 mg/L'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='nitrite',
            field=models.FloatField(blank=True, null=True, verbose_name='亞硝酸鹽 mg/L'),
        ),
        migrations.CreateModel(
            name='PondSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sensor_type', models.CharField(choices=[('multi', '多合一感測器'), ('do', '溶氧感測器'), ('ph', 'pH 感測器'), ('chem', '氨氮/亞硝酸鹽'), ('temp', '溫度感測器')], default='multi', max_length=20)),
                ('x_position', models.PositiveSmallIntegerField(default=50, help_text='地圖上的水平位置，0 到 100。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y_position', models.PositiveSmallIntegerField(default=50, help_text='地圖上的垂直位置，0 到 100。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='water.pond')),
            ],
            options={
                'ordering': ['pond', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='water.pondsensor'),
        ),
        migrations.CreateModel(
            name='WaterThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('dissolved_oxygen', '溶氧量'), ('ph', 'pH 值'), ('ammonia_nitrogen', '氨氮'), ('nitrite', '亞硝酸鹽'), ('temperature', '溫度')], max_length=40)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='water.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pond', 'metric'],
                'unique_together': {('user', 'pond', 'metric')},
            },
        ),
    ]
