# Generated by Django 6.0.3 on 2026-06-10 01:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_add_default_sensors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterthreshold',
            options={'ordering': ['pond', 'sensor', 'metric']},
        ),
        migrations.AlterUniqueTogether(
            name='waterthreshold',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pond',
            name='inlet_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='進水口 X 座標'),
        ),
        migrations.AddField(
            model_name='pond',
            name='inlet_y',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='進水口 Y 座標'),
        ),
        migrations.AddField(
            model_name='pond',
            name='outlet_x',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='排水口 X 座標'),
        ),
        migrations.AddField(
            model_name='pond',
            name='outlet_y',
            field=models.PositiveSmallIntegerField(default=95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='排水口 Y 座標'),
        ),
        migrations.AddField(
            model_name='waterthreshold',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='water.pondsensor', verbose_name='專屬感測器'),
        ),
        migrations.AlterUniqueTogether(
            name='waterthreshold',
            unique_together={('user', 'pond', 'sensor', 'metric')},
        ),
    ]
