# Generated by Django 6.0.3 on 2026-06-10 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alter_waterthreshold_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewer_ponds', to=settings.AUTH_USER_MODEL, verbose_name='協作者 (唯讀)'),
        ),
    ]
