# Generated by Django 6.0.3 on 2026-06-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_pond_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='stability_w_do',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='穩定度-溶氧權重'),
        ),
        migrations.AddField(
            model_name='pond',
            name='stability_w_ph',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='穩定度-pH權重'),
        ),
        migrations.AddField(
            model_name='pond',
            name='stability_w_temp',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='穩定度-溫度權重'),
        ),
        migrations.AddField(
            model_name='pondsensor',
            name='secret_token',
            field=models.CharField(blank=True, help_text='感測器上傳讀值時使用的唯一驗證金鑰。', max_length=64, null=True, unique=True, verbose_name='上傳金鑰 (Token)'),
        ),
    ]
