# Generated by Django 6.0.3 on 2026-06-10 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_pond_stability_w_do_pond_stability_w_ph_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondsensor',
            name='sensor_type',
            field=models.CharField(choices=[('multi', '📟 多合一感測器'), ('do', '💨 溶氧感測器'), ('ph', '💧 pH 感測器'), ('chem', '# 氨氮/亞硝酸鹽'), ('temp', '🌡️ 溫度感測器')], default='multi', max_length=20),
        ),
        migrations.CreateModel(
            name='WaterSimulationCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Water simulation', max_length=80)),
                ('is_enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.PositiveIntegerField(default=500)),
                ('anomaly_rate', models.FloatField(default=0.2)),
                ('anomaly_mode', models.CharField(choices=[('mixed', 'Mixed'), ('pond', 'Whole pond'), ('sensor', 'Single sensor')], default='mixed', max_length=20)),
                ('anomaly_duration_rounds', models.PositiveIntegerField(default=3)),
                ('active_anomaly_scope', models.CharField(blank=True, choices=[('', 'None'), ('pond', 'Whole pond'), ('sensor', 'Single sensor')], default='', max_length=20)),
                ('active_anomaly_type', models.CharField(blank=True, default='', max_length=30)),
                ('active_anomaly_remaining_rounds', models.PositiveIntegerField(default=0)),
                ('active_anomaly_sensor_index', models.PositiveIntegerField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_anomaly_pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='water.pond')),
                ('ponds', models.ManyToManyField(blank=True, related_name='simulation_crons', to='water.pond')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_simulation_crons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
