# Generated by Django 6.0.3 on 2026-06-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_alter_pondsensor_sensor_type_watersimulationcron'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ponds', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
    ]
