# Generated by Django 6.0.3 on 2026-06-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_pond_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersimulationcron',
            name='discord_notify_interval_seconds',
            field=models.PositiveIntegerField(default=300, verbose_name='Discord 判讀間隔 (秒)'),
        ),
        migrations.AddField(
            model_name='watersimulationcron',
            name='discord_webhook_url',
            field=models.CharField(blank=True, default='https://discord.com/api/webhooks/1514235317312290827/jr__idPlLOwpvlGs74QO4VdSVgYWb0VwZue6EH2O9m4pgE8ntdPrM35lRzZ90T9nomQI', max_length=500, verbose_name='Discord Webhook URL'),
        ),
        migrations.AddField(
            model_name='watersimulationcron',
            name='last_discord_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discord 上次執行時間'),
        ),
        migrations.CreateModel(
            name='WaterSensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('dissolved_oxygen', '溶氧量'), ('ph', 'pH 值'), ('ammonia_nitrogen', '氨氮'), ('nitrite', '亞硝酸鹽'), ('temperature', '溫度')], max_length=40, verbose_name='指標')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟動中')),
                ('first_triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='首次觸發時間')),
                ('last_triggered_at', models.DateTimeField(auto_now=True, verbose_name='最近觸發時間')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢復正常時間')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='water.pondsensor', verbose_name='感測器')),
            ],
            options={
                'verbose_name': '感測器警報',
                'verbose_name_plural': '感測器警報列表',
                'ordering': ['-first_triggered_at'],
            },
        ),
    ]
