# Generated by Django 6.0.3 on 2026-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_watersimulationcron_discord_notify_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='discord_webhook_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Discord Webhook URL'),
        ),
    ]
