# Generated by Django 6.0.3 on 2026-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_pond_discord_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersimulationcron',
            name='discord_suppression_interval_seconds',
            field=models.PositiveIntegerField(default=3600, verbose_name='相同項目避免重複通知間隔 (秒)'),
        ),
        migrations.AlterField(
            model_name='watersimulationcron',
            name='discord_webhook_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Discord Webhook URL'),
        ),
    ]
