# Generated by Django 6.0.3 on 2026-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_watersimulationcron_discord_suppression_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersensoralert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次通知時間'),
        ),
    ]
