# Generated by Django 6.0.3 on 2026-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0012_watersensoralert_last_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersimulationcron',
            name='discord_is_enabled',
            field=models.BooleanField(default=False, verbose_name='啟用 Discord 警報通知'),
        ),
        migrations.AddField(
            model_name='watersimulationcron',
            name='discord_last_result',
            field=models.TextField(blank=True, default='', verbose_name='Discord 上次執行結果'),
        ),
    ]
