# Generated by Django 6.0.3 on 2026-06-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0013_watersimulationcron_discord_is_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersimulationcron',
            name='asr_backup_url',
            field=models.CharField(blank=True, default='', help_text='主要 URL 無法連線時的備用 URL', max_length=500, verbose_name='語音辨識 API URL（備用）'),
        ),
        migrations.AddField(
            model_name='watersimulationcron',
            name='asr_url',
            field=models.CharField(blank=True, default='', help_text='Colab/ngrok 等語音辨識服務的主要 URL，例如 https://xxxx.ngrok-free.app', max_length=500, verbose_name='語音辨識 API URL（主要）'),
        ),
    ]
