# Generated by Django 6.0.3 on 2026-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0014_add_asr_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='pond_maps/', verbose_name='感測器分佈地圖圖片'),
        ),
    ]
