# Generated by Django 6.0.3 on 2026-06-11 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0016_pond_is_public_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondAerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='水車名稱')),
                ('x_position', models.PositiveSmallIntegerField(default=50, help_text='地圖上的水平位置，0 到 100。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='X 座標')),
                ('y_position', models.PositiveSmallIntegerField(default=50, help_text='地圖上的垂直位置，0 到 100。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Y 座標')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('rules', models.JSONField(blank=True, default=list, verbose_name='運作規則')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aerators', to='water.pond')),
            ],
        ),
    ]
