# Generated by Django 6.0.3 on 2026-06-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0017_pondaerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondaerator',
            name='last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次判斷時間'),
        ),
        migrations.AddField(
            model_name='pondaerator',
            name='last_evaluation_reason',
            field=models.TextField(blank=True, default='', verbose_name='上次判斷說明'),
        ),
        migrations.AddField(
            model_name='pondaerator',
            name='last_is_operating',
            field=models.BooleanField(default=False, verbose_name='上次判斷是否運作'),
        ),
    ]
