# Generated by Django 6.0.3 on 2026-06-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0018_pondaerator_last_evaluated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondAeratorStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('is_operating', models.BooleanField(verbose_name='是否運作')),
                ('reason', models.TextField(blank=True, default='', verbose_name='判斷說明')),
                ('aerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='water.pondaerator')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aerator_state_logs', to='water.pond')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['pond', 'aerator', '-recorded_at'], name='water_ponda_pond_id_02421b_idx')],
            },
        ),
    ]
