# Generated by Django 6.0.3 on 2026-06-13 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0019_pondaeratorstatelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArFeedLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(max_length=80)),
                ('player_name', models.CharField(max_length=80)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scene', models.CharField(default='clam_polyculture', max_length=40)),
                ('badge', models.CharField(blank=True, default='', max_length=120)),
                ('result_text', models.TextField(blank=True, default='')),
                ('growth', models.FloatField(default=0)),
                ('water', models.JSONField(blank=True, default=dict)),
                ('played_on', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_feed_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'updated_at'],
                'constraints': [models.UniqueConstraint(fields=('played_on', 'player_key'), name='unique_ar_feed_daily_player')],
            },
        ),
    ]
