"""
Django settings for shuijing project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$1t6m4+j566!n#+gtbi+*pt@3o))nf1omld75y61_7s+j$0^fk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #[Login Apps]
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    'django_bootstrap5',
    'accounts',
    'core',
    'guide',
    'chat',
    'water',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',

]

ROOT_URLCONF = "shuijing.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR /'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.user_display_name",
            ],
        },
    },
]

WSGI_APPLICATION = "shuijing.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



#[Login Apps]
SITE_ID = 1
# ── allauth 基本設定 ──
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# 點 Google 登入直接跳，不停在 allauth 的中間確認頁
SOCIALACCOUNT_LOGIN_ON_GET = True

# 登入 / 登出後的跳轉
LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/'

# Session cookie（本地開發）
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE   = False
SOCIALACCOUNT_LOGIN_ON_GET = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

ACCOUNT_LOGOUT_ON_GET = False   # 禁止 GET 直接登出
LOGIN_URL = '/'                  # 直接訪問 /accounts/login 導回首頁

# TOAST通知
ACCOUNT_EMAIL_VERIFICATION = 'none'
# allauth 預設會自動送 messages，確認沒有關掉就好
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'

# 自定義設定
ACTIVITIES_PER_PAGE = 9


MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/'



# Email 設定（Gmail SMTP）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', EMAIL_HOST_USER)

# ==========================================
# 網站管理後台 (SimpleUI) 設定
# ==========================================
SIMPLEUI_HOME_INFO = False
SIMPLEUI_LOGO = ''
SIMPLEUI_DEFAULT_THEME = 'e-black-pro.css'
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['活動管理', '內容與連結', 'USR 實踐', '數位導覽', '系統管理', '封存項目'],
    'dynamic': False,
    'menus': [
        {
            'name': '活動管理',
            'icon': 'fas fa-calendar-check',
            'models': [
                {'name': '活動資訊', 'url': 'core/activity/', 'icon': 'fas fa-star'},
                {'name': '報名記錄', 'url': 'core/registration/', 'icon': 'fas fa-file-signature'},
            ]
        },
        {
            'name': '內容與連結',
            'icon': 'fas fa-edit',
            'models': [
                {'name': '首頁輪播', 'url': 'core/heroslide/', 'icon': 'fas fa-images'},
                {'name': '最新公告', 'url': 'core/notice/', 'icon': 'fas fa-bullhorn'},
                {'name': '在地商家與連結', 'url': 'core/relatedlink/', 'icon': 'fas fa-store'},
                {'name': '聯絡訊息', 'url': 'core/contactmessage/', 'icon': 'fas fa-envelope-open-text'},
            ]
        },
        {
            'name': 'USR 實踐',
            'icon': 'fas fa-graduation-cap',
            'models': [
                {'name': 'AIoT 專案', 'url': 'core/aiotproject/', 'icon': 'fas fa-microchip'},
                {'name': '師生成果紀錄', 'url': 'core/usrachievement/', 'icon': 'fas fa-award'},
                {'name': '影音成果', 'url': 'core/usrvideo/', 'icon': 'fas fa-play-circle'},
            ]
        },
        {
            'name': '數位導覽',
            'icon': 'fas fa-map-marked-alt',
            'models': [
                {'name': '導覽景點', 'url': 'guide/storyspot/', 'icon': 'fas fa-map-marker-alt'},
                {'name': 'AR 素材管理', 'url': 'guide/arasset/', 'icon': 'fas fa-vr-cardboard'},
                {'name': '景點知識說明', 'url': 'guide/storyfact/', 'icon': 'fas fa-book-reader'},
            ]
        },
        {
            'name': '系統管理',
            'icon': 'fas fa-cogs',
            'models': [
                {'name': '使用者', 'url': 'auth/user/', 'icon': 'fas fa-user-shield'},
                {'name': '群組', 'url': 'auth/group/', 'icon': 'fas fa-users-cog'},
                {'name': '社交帳號', 'url': 'socialaccount/socialaccount/', 'icon': 'fas fa-share-alt'},
            ]
        },
        {
            'name': '封存項目',
            'icon': 'fas fa-archive',
            'models': [
                {'name': 'USR 團隊成員', 'url': 'core/usrteammember/', 'icon': 'fas fa-user-times'},
                {'name': '首頁服務項目', 'url': 'core/serviceitem/', 'icon': 'fas fa-trash-alt'},
            ]
        }
    ]
}
